name: Build

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  tests:
    permissions:
      contents: write
    uses: ./.github/workflows/tests.yaml

  publish:
    if: ${{ github.event_name != 'pull_request' }}
    needs: tests
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish.yaml

  release:
    if: ${{ github.event_name != 'pull_request' }}
    needs: publish
    permissions:
      contents: write
    uses: ./.github/workflows/changelog.yaml

  documentation:
    if: ${{ github.event_name != 'pull_request' }}
    needs: publish
    permissions:
      contents: write
    uses: ./.github/workflows/documentation.yaml
